### ISSUE TITLE
Error installing jpegoptim

### ISSUE THREAD

**Issue by ianpogi5** [1000ch/grunt-image#20]
Nothing happening when running grunt

Installation error:
```
> jpegoptim-bin@2.0.1 postinstall /Users/ian/Projects/fynd_hexo/node_modules/grunt-image/node_modules/jpegoptim-bin
> node lib/install.js

  ⚠ The `jpegoptim` binary doesn't seem to work correctly
  ⚠ jpegoptim pre-build test failed
  ℹ compiling from source
  ✖ Error: ./configure --prefix="/Users/ian/Projects/fynd_hexo/node_modules/grunt-image/node_modules/jpegoptim-bin/vendor" --bindir="/Users/ian/Projects/fynd_hexo/node_modules/grunt-image/node_modules/jpegoptim-bin/vendor" && make install && mv /Users/ian/Projects/fynd_hexo/node_modules/grunt-image/node_modules/jpegoptim-bin/vendor/bin/jpegoptim /Users/ian/Projects/fynd_hexo/node_modules/grunt-image/node_modules/jpegoptim-bin/vendor/jpegoptim
Command failed: /bin/sh -c ./configure --prefix="/Users/ian/Projects/fynd_hexo/node_modules/grunt-image/node_modules/jpegoptim-bin/vendor" --bindir="/Users/ian/Projects/fynd_hexo/node_modules/grunt-image/node_modules/jpegoptim-bin/vendor"

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
```

Part of my gruntfile
```
image: {
            static: {
                options: {
                    pngquant: true,
                    optipng: true,
                    advpng: true,
                    zopflipng: true,
                    pngcrush: true,
                    pngout: true,
                    mozjpeg: true,
                    jpegRecompress: true,
                    jpegoptim: false,
                    gifsicle: true,
                    svgo: true
                },
                files: {
                    'themes/fynd/source/images/fynd.png': 'themes/fynd/source/images/optfynd.png'
                }
            },
            dynamic: {
              files: [{
                expand: true,
                cwd: 'public/',
                src: ['**/*.{png,jpg,jpeg,gif,svg}'],
                dest: 'public/'
              }]
            }

grunt.registerTask('image', ['image:dynamic']);
```

Running `grunt --verbose --debug` shows the error below:
```
Registering "grunt-image" local Npm module tasks.
Reading /Users/ian/Projects/fynd_hexo/node_modules/grunt-image/package.json...OK
Parsing /Users/ian/Projects/fynd_hexo/node_modules/grunt-image/package.json...OK
Loading "image.js" tasks...OK
+ image
Loading "optimizer.js" tasks...OK
>> No tasks were registered or unregistered.
Loading "round10.js" tasks...OK
>> No tasks were registered or unregistered.


Running tasks: image

Running "image" task
[D] Task source: /Users/ian/Projects/fynd_hexo/Gruntfile.js

Running "image:dynamic" (image) task
[D] Task source: /Users/ian/Projects/fynd_hexo/Gruntfile.js

Running "image:dynamic" (image) task
[D] Task source: /Users/ian/Projects/fynd_hexo/Gruntfile.js

thousands more of the above "Running..."
```

Looks like an endless loop.

Any ideas?

**Comment by 1000ch** [comment]
Newest version depends jpegoptim `v3.0.0`. Would you try to reinstall?
