### ISSUE TITLE
grunt-image and Node v6.1.0

### ISSUE THREAD

**Issue by derbronko** [1000ch/grunt-image#21]
Unfortunaly, there is an error with your grunt package and Node v6.1.0 and Windows 7.

Here is the stacktrace when trying to list grunt tasks:
```
Registering "grunt-image" local Npm module tasks.
Reading[...]\git_workspace\[...]\node_modules\grunt-image\package.json...OK
Parsing [...]\git_workspace\[...]\node_modules\grunt-image\package.json...OK
Loading "image.js" tasks...OK
+ image
Loading "optimizer.js" tasks...ERROR
>> ReferenceError: grunt is not defined
>>   at Object.Optimizer ([...]\git_workspace\[...]\node_modules\grunt-image\tasks\optimizer.js:15:3)
>>   at loadTask ([...]\git_workspace\[...]\node_modules\grunt\lib\grunt\task.js:318:10)
>>   at [...]\git_workspace\[...]\node_modules\grunt\lib\grunt\task.js:354:7
>>   at Array.forEach (native)
>>   at loadTasks ([...]\git_workspace\[...]\node_modules\grunt\lib\grunt\task.js:353:11)
>>   at Task.task.loadNpmTasks ([...]\git_workspace\[...]\node_modules\grunt\lib\grunt\task.js:401:5)
>>   at Array.forEach (native)
>>   at module.exports ([...]\git_workspace\[...]\node_modules\load-grunt-tasks\index.js:25:29)
>>   at module.exports ([...]\git_workspace\[...]\node_modules\load-grunt-config\index.js:67:32)
>>   at Object.module.exports ([...]\git_workspace\[...]\Gruntfile.js:3:30)
>>   at loadTask ([...]\git_workspace\[...]\node_modules\grunt\lib\grunt\task.js:318:10)
>>   at Task.task.init ([...]\git_workspace\[...]\node_modules\grunt\lib\grunt\task.js:437:5)
>>   at Object.grunt.tasks ([...]\git_workspace\[...]\node_modules\grunt\lib\grunt.js:111:8)
>>   at Object.module.exports [as cli] ([...]git_workspace\[...]\node_modules\grunt\lib\grunt\cli.js:27:9)
>>   at Object.<anonymous> (%USER%\AppData\Roaming\npm\node_modules\grunt-cli\bin\grunt:45:20)
>>   at Module._compile (module.js:541:32)
>>   at Object.Module._extensions..js (module.js:550:10)
>>   at Module.load (module.js:456:32)
>>   at tryModuleLoad (module.js:415:12)
>>   at Function.Module._load (module.js:407:3)
>>   at Function.Module.runMain (module.js:575:10)
>>   at startup (node.js:160:18)
>>   at node.js:445:3
Loading "round10.js" tasks...OK
>> No tasks were registered or unregistered.
```

It seems, that `path.extname(this.src)` is returning no string anymore.

**Comment by 1000ch** [comment]
Thank you for reporting. For the moment, please update to `v1.5.1`.
And I'm rewriting.
