### ISSUE TITLE
bug(guetzli): pre-build test failed

### ISSUE THREAD

**Issue by Kristinita** [1000ch/grunt-image#34]
### 1. Summary

I get stack trace in console, when I install grunt-image.

### 2. Environment

+ Windows 10 Enterprise LTSB 64-bit EN,
+ Node.js 9.6.0,
+ grunt-cli 1.0.2,
+ grunt-image 4.2.0.

### 3. Steps to reproduce

I [**create `package.json` in new folder**](https://stackoverflow.com/a/49053110/5951529) → I install grunt-image.

### 4. Expected behavior

No stack trace in console.

### 5. Actual behavior

Stack trace:

```shell
> guetzli@1.0.1 postinstall D:\SashaDemoRepositories\SashaGruntDebugging\node_modules\guetzli
> node lib/install.js

  ‼ The `D:\SashaDemoRepositories\SashaGruntDebugging\node_modules\guetzli\vendor\guetzli.exe` binary doesn't seem to work correctly
  ‼ guetzli pre-build test failed
  i compiling from source
  × Error: mkdir -p D:\SashaDemoRepositories\SashaGruntDebugging\node_modules\guetzli\vendor && make && mv bin/Release/guetzli.exe D:\SashaDemoRepositories\SashaGruntDebugging\node_modules\guetzli\vendor\guetzli.exe
Command failed: mkdir -p D:\SashaDemoRepositories\SashaGruntDebugging\node_modules\guetzli\vendor
A subdirectory or file D:\SashaDemoRepositories\SashaGruntDebugging\node_modules\guetzli\vendor already exists.
Error occurred while processing: D:\SashaDemoRepositories\SashaGruntDebugging\node_modules\guetzli\vendor.

    at ChildProcess.exithandler (child_process.js:272:12)
    at ChildProcess.emit (events.js:125:13)
    at maybeClose (internal/child_process.js:933:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
```

Full output:

```shell
D:\SashaDemoRepositories\SashaGruntDebugging>npm install --save-dev grunt-image

> gifsicle@3.0.4 postinstall D:\SashaDemoRepositories\SashaGruntDebugging\node_modules\gifsicle
> node lib/install.js

  √ gifsicle pre-build test passed successfully

> optipng-bin@4.0.0 postinstall D:\SashaDemoRepositories\SashaGruntDebugging\node_modules\grunt-image\node_modules\optipng-bin
> node lib/install.js

  √ optipng pre-build test passed successfully

> guetzli@1.0.1 postinstall D:\SashaDemoRepositories\SashaGruntDebugging\node_modules\guetzli
> node lib/install.js

  ‼ The `D:\SashaDemoRepositories\SashaGruntDebugging\node_modules\guetzli\vendor\guetzli.exe` binary doesn't seem to work correctly
  ‼ guetzli pre-build test failed
  i compiling from source
  × Error: mkdir -p D:\SashaDemoRepositories\SashaGruntDebugging\node_modules\guetzli\vendor && make && mv bin/Release/guetzli.exe D:\SashaDemoRepositories\SashaGruntDebugging\node_modules\guetzli\vendor\guetzli.exe
Command failed: mkdir -p D:\SashaDemoRepositories\SashaGruntDebugging\node_modules\guetzli\vendor
A subdirectory or file D:\SashaDemoRepositories\SashaGruntDebugging\node_modules\guetzli\vendor already exists.
Error occurred while processing: D:\SashaDemoRepositories\SashaGruntDebugging\node_modules\guetzli\vendor.

    at ChildProcess.exithandler (child_process.js:272:12)
    at ChildProcess.emit (events.js:125:13)
    at maybeClose (internal/child_process.js:933:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)

> jpeg-recompress-bin@3.0.1 postinstall D:\SashaDemoRepositories\SashaGruntDebugging\node_modules\jpeg-recompress-bin
> node lib/install.js

  √ jpeg-recompress pre-build test passed successfully

> mozjpeg@5.0.0 postinstall D:\SashaDemoRepositories\SashaGruntDebugging\node_modules\mozjpeg
> node lib/install.js

  √ mozjpeg pre-build test passed successfully

> pngquant-bin@3.1.1 postinstall D:\SashaDemoRepositories\SashaGruntDebugging\node_modules\pngquant-bin
> node lib/install.js

  √ pngquant pre-build test passed successfully

> zopflipng-bin@4.1.0 postinstall D:\SashaDemoRepositories\SashaGruntDebugging\node_modules\zopflipng-bin
> node lib/install.js

  √ zopflipng pre-build test passed successfully
+ grunt-image@4.2.0
added 379 packages from 211 contributors in 95.062s
```

Thanks.

**Comment by 1000ch** [comment]
@Kristinita It seems it's problem guetzli-self, not grunt-image, isn't it? Do you file a issue on guetzli repo?
